/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, x86_64-w64-mingw32-g++ 16.1.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module binary_to_gray(binary, gray);
  input [3:0] binary;
  wire [3:0] binary;
  output [3:0] gray;
  wire [3:0] gray;
  \$_XOR_  _0_ (
    .A(binary[0]),
    .B(binary[1]),
    .Y(gray[0])
  );
  \$_XOR_  _1_ (
    .A(binary[1]),
    .B(binary[2]),
    .Y(gray[1])
  );
  \$_XOR_  _2_ (
    .A(binary[2]),
    .B(binary[3]),
    .Y(gray[2])
  );
  assign gray[3] = binary[3];
endmodule
